### ISSUE TITLE
Where is uglify dependencie?

### ISSUE THREAD

**Issue by felquis** [EvandroLG/selecting#5]
When I run 'make minify' I get an error because there's no uglify in the dependencies https://github.com/EvandroLG/selecting/blob/5492f295791abac490a121899475c0c9751ef938/package.json#L7-L10

**Comment by EvandroLG** [comment]
I forgot to put it in the package.json.
Make a git pull, run npm install and then  run make minify. It should be enough.
Let me know if it works for you.

**Comment by felquis** [comment]
Yeah it's working now, thanks :)

**Comment by felquis** [comment]
Closed by https://github.com/EvandroLG/selecting/commit/48328831975834838f593040a15bad335e5c14f3
